name: surveysdk_flutter
description: Flutter plugin for Survey SDK - collect user feedback and surveys
version: 1.0.0
homepage: https://github.com/mustafadenizer-c4f/surveysdk-flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.surveysdk.flutter
        pluginClass: SurveySdkPlugin
      ios:
        pluginClass: SurveySDKPlugin